name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install Allure commandline
      run: |
        sudo npm install -g allure-commandline --unsafe-perm=true
    
    - name: Build & Install
      run: dotnet build

    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net9.0/playwright.ps1 install

    - name: Run your tests
      run: |
          dotnet test --no-build \
            --logger "console;verbosity=normal" \
            -- NUnit.Allure.Configuration.ResultsDirectory=bin/Debug/net9.0/allure-results

    - name: List Allure output directory
      run: ls -R bin/Debug/net9.0/allure-results || echo "No results found"

    - name: Copy Allure results to a stable path
      run: |
        mkdir -p ./temp-allure-results
        cp -r bin/Debug/net9.0/allure-results/* ./temp-allure-results

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: bin/Debug/net9.0/allure-results

    - name: Generate Allure HTML Report
      run: |
        allure generate temp-allure-results --clean -o allure-report

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: temp-allure-results


 