name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install Allure commandline
      run: sudo npm install -g allure-commandline --unsafe-perm=true
    
    - name: Build & Install
      run: dotnet build

    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net9.0/playwright.ps1 install

    - name: Run your tests
      env:
        TEST_ENV: dev
        USERNAME: ${{ secrets.USERNAME }}
        USERPASSWORD: ${{ secrets.USERPASSWORD }}
        GITHUB_ACTIONS: true
      run: |
          dotnet test --no-build \
            --logger "console;verbosity=normal" \
            -- NUnit.Allure.Configuration.ResultsDirectory=allure-results    

    - name: List bin directory contents
      run: ls -la bin/Debug/net9.0

    - name: List allure-results folder (if exists)
      run: ls -la bin/Debug/net9.0/allure-report || echo "allure-results folder not found"

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: bin/Debug/net9.0/allure-report

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: bin/Debug/net9.0/allure-report

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: bin/Debug/net9.0/allure-report


 